package dnomyar.rxgag.models.db.sqlite;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import dnomyar.rxgag.models.db.sqlite.Gag;
import dnomyar.rxgag.models.db.sqlite.GagList;
import dnomyar.rxgag.models.db.sqlite.GagListItem;

import dnomyar.rxgag.models.db.sqlite.GagDao;
import dnomyar.rxgag.models.db.sqlite.GagListDao;
import dnomyar.rxgag.models.db.sqlite.GagListItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gagDaoConfig;
    private final DaoConfig gagListDaoConfig;
    private final DaoConfig gagListItemDaoConfig;

    private final GagDao gagDao;
    private final GagListDao gagListDao;
    private final GagListItemDao gagListItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gagDaoConfig = daoConfigMap.get(GagDao.class).clone();
        gagDaoConfig.initIdentityScope(type);

        gagListDaoConfig = daoConfigMap.get(GagListDao.class).clone();
        gagListDaoConfig.initIdentityScope(type);

        gagListItemDaoConfig = daoConfigMap.get(GagListItemDao.class).clone();
        gagListItemDaoConfig.initIdentityScope(type);

        gagDao = new GagDao(gagDaoConfig, this);
        gagListDao = new GagListDao(gagListDaoConfig, this);
        gagListItemDao = new GagListItemDao(gagListItemDaoConfig, this);

        registerDao(Gag.class, gagDao);
        registerDao(GagList.class, gagListDao);
        registerDao(GagListItem.class, gagListItemDao);
    }
    
    public void clear() {
        gagDaoConfig.getIdentityScope().clear();
        gagListDaoConfig.getIdentityScope().clear();
        gagListItemDaoConfig.getIdentityScope().clear();
    }

    public GagDao getGagDao() {
        return gagDao;
    }

    public GagListDao getGagListDao() {
        return gagListDao;
    }

    public GagListItemDao getGagListItemDao() {
        return gagListItemDao;
    }

}
