package dnomyar.rxgag.models.db.sqlite;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GAG".
 */
public class Gag {

    private Long id;
    private Long updateTime;
    private Long createdAt;
    private String gagId;
    private String title;
    private String image;
    private Long score;

    public Gag() {
    }

    public Gag(Long id) {
        this.id = id;
    }

    public Gag(Long id, Long updateTime, Long createdAt, String gagId, String title, String image, Long score) {
        this.id = id;
        this.updateTime = updateTime;
        this.createdAt = createdAt;
        this.gagId = gagId;
        this.title = title;
        this.image = image;
        this.score = score;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    public Long getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    public String getGagId() {
        return gagId;
    }

    public void setGagId(String gagId) {
        this.gagId = gagId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Long getScore() {
        return score;
    }

    public void setScore(Long score) {
        this.score = score;
    }

}
