package dnomyar.rxgag.models.db.sqlite;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import dnomyar.rxgag.models.db.sqlite.GagListItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GAG_LIST_ITEM".
*/
public class GagListItemDao extends AbstractDao<GagListItem, Long> {

    public static final String TABLENAME = "GAG_LIST_ITEM";

    /**
     * Properties of entity GagListItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UpdateTime = new Property(1, Long.class, "updateTime", false, "UPDATE_TIME");
        public final static Property CreatedAt = new Property(2, Long.class, "createdAt", false, "CREATED_AT");
        public final static Property ListKey = new Property(3, String.class, "listKey", false, "LIST_KEY");
        public final static Property GagDBId = new Property(4, Long.class, "gagDBId", false, "GAG_DBID");
        public final static Property GagId = new Property(5, String.class, "gagId", false, "GAG_ID");
    };

    private DaoSession daoSession;


    public GagListItemDao(DaoConfig config) {
        super(config);
    }
    
    public GagListItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GAG_LIST_ITEM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"UPDATE_TIME\" INTEGER," + // 1: updateTime
                "\"CREATED_AT\" INTEGER," + // 2: createdAt
                "\"LIST_KEY\" TEXT," + // 3: listKey
                "\"GAG_DBID\" INTEGER," + // 4: gagDBId
                "\"GAG_ID\" TEXT);"); // 5: gagId
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_GAG_LIST_ITEM_LIST_KEY_GAG_DBID ON GAG_LIST_ITEM" +
                " (\"LIST_KEY\",\"GAG_DBID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GAG_LIST_ITEM\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GagListItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindLong(2, updateTime);
        }
 
        Long createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindLong(3, createdAt);
        }
 
        String listKey = entity.getListKey();
        if (listKey != null) {
            stmt.bindString(4, listKey);
        }
 
        Long gagDBId = entity.getGagDBId();
        if (gagDBId != null) {
            stmt.bindLong(5, gagDBId);
        }
 
        String gagId = entity.getGagId();
        if (gagId != null) {
            stmt.bindString(6, gagId);
        }
    }

    @Override
    protected void attachEntity(GagListItem entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GagListItem readEntity(Cursor cursor, int offset) {
        GagListItem entity = new GagListItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // updateTime
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // createdAt
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // listKey
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // gagDBId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // gagId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GagListItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUpdateTime(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setCreatedAt(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setListKey(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setGagDBId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setGagId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GagListItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GagListItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getGagDao().getAllColumns());
            builder.append(" FROM GAG_LIST_ITEM T");
            builder.append(" LEFT JOIN GAG T0 ON T.\"GAG_DBID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected GagListItem loadCurrentDeep(Cursor cursor, boolean lock) {
        GagListItem entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Gag gag = loadCurrentOther(daoSession.getGagDao(), cursor, offset);
        entity.setGag(gag);

        return entity;    
    }

    public GagListItem loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<GagListItem> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<GagListItem> list = new ArrayList<GagListItem>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<GagListItem> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<GagListItem> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
