package dnomyar.rxgag.models.db.sqlite;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import dnomyar.rxgag.models.db.sqlite.GagList;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GAG_LIST".
*/
public class GagListDao extends AbstractDao<GagList, Long> {

    public static final String TABLENAME = "GAG_LIST";

    /**
     * Properties of entity GagList.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UpdateTime = new Property(1, Long.class, "updateTime", false, "UPDATE_TIME");
        public final static Property CreatedAt = new Property(2, Long.class, "createdAt", false, "CREATED_AT");
        public final static Property ListKey = new Property(3, String.class, "listKey", false, "LIST_KEY");
        public final static Property NextOffSet = new Property(4, String.class, "nextOffSet", false, "NEXT_OFF_SET");
        public final static Property HasNext = new Property(5, Boolean.class, "hasNext", false, "HAS_NEXT");
    };


    public GagListDao(DaoConfig config) {
        super(config);
    }
    
    public GagListDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GAG_LIST\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"UPDATE_TIME\" INTEGER," + // 1: updateTime
                "\"CREATED_AT\" INTEGER," + // 2: createdAt
                "\"LIST_KEY\" TEXT," + // 3: listKey
                "\"NEXT_OFF_SET\" TEXT," + // 4: nextOffSet
                "\"HAS_NEXT\" INTEGER);"); // 5: hasNext
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_GAG_LIST_LIST_KEY ON GAG_LIST" +
                " (\"LIST_KEY\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GAG_LIST\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GagList entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindLong(2, updateTime);
        }
 
        Long createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindLong(3, createdAt);
        }
 
        String listKey = entity.getListKey();
        if (listKey != null) {
            stmt.bindString(4, listKey);
        }
 
        String nextOffSet = entity.getNextOffSet();
        if (nextOffSet != null) {
            stmt.bindString(5, nextOffSet);
        }
 
        Boolean hasNext = entity.getHasNext();
        if (hasNext != null) {
            stmt.bindLong(6, hasNext ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GagList readEntity(Cursor cursor, int offset) {
        GagList entity = new GagList( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // updateTime
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // createdAt
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // listKey
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // nextOffSet
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0 // hasNext
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GagList entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUpdateTime(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setCreatedAt(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setListKey(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNextOffSet(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setHasNext(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GagList entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GagList entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
