package dnomyar.rxgag.models.db.sqlite;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GAG_LIST".
 */
public class GagList {

    private Long id;
    private Long updateTime;
    private Long createdAt;
    private String listKey;
    private String nextOffSet;
    private Boolean hasNext;

    public GagList() {
    }

    public GagList(Long id) {
        this.id = id;
    }

    public GagList(Long id, Long updateTime, Long createdAt, String listKey, String nextOffSet, Boolean hasNext) {
        this.id = id;
        this.updateTime = updateTime;
        this.createdAt = createdAt;
        this.listKey = listKey;
        this.nextOffSet = nextOffSet;
        this.hasNext = hasNext;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    public Long getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    public String getListKey() {
        return listKey;
    }

    public void setListKey(String listKey) {
        this.listKey = listKey;
    }

    public String getNextOffSet() {
        return nextOffSet;
    }

    public void setNextOffSet(String nextOffSet) {
        this.nextOffSet = nextOffSet;
    }

    public Boolean getHasNext() {
        return hasNext;
    }

    public void setHasNext(Boolean hasNext) {
        this.hasNext = hasNext;
    }

}
